// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.gradleToolsVersion = '9.2.0'

    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:${gradleToolsVersion}"
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
    }
}

ext {
    apkNamePrefix = 'DataStats'
    versionName = "3.0.0"
    versionCode = 35

    compileSdkVersion = 36
    buildToolsVersion = '36.0.0'

    targetSdkVersion = 35
    minSdkVersion = 23
}