name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # GitHub Actionsのタイムラインの可視化
    - uses: Kesin11/actions-timeline@v2

    - uses: actions/checkout@v4

    - name: set up JDK 11, 17
      uses: actions/setup-java@v4
      with:
        java-version: |
          11
          17
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle Cacge
      uses: gradle/gradle-build-action@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
